version: "3"
services:
  #php app
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_intranet_nacional
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: API_INTRANET_NACIONAL
      SERVICE_TAGS: LOCAL
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - api-intranet-nacional-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  vite:
    image: node:20
    container_name: laravel_vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
  #nginx service
  webserver:
    image: nginx:alpine
    container_name: nginx_intranet_nacional
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    networks: 
      - api-intranet-nacional-network
    volumes:
     - ./:/var/www:Z
     - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - api
    #MySql Service
  #database:
  #  image: mysql:8.0.30
  #  container_name: sql_intranet_nacional
  #  restart: unless-stopped
  #  tty: true
  #  ports:
  #    - "3307:3306"
  #  environment:
  #    MYSQL_DATABASE: ${DB_DATABASE}
  #    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #    MYSQL_PASSWORD: ${DB_PASSWORD}
  #    MYSQL_USER: ${DB_USERNAME}
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: mysql  
  #  volumes:
  #    - mysql-data:/var/lib/mysql
  #    - ./mysql/my.cnf:/etc/mysql/my.cnf
  #  networks: 
  #    - api-intranet-nacional-network
#Docker Networks
networks:
  api-intranet-nacional-network:
    driver: bridge      
#volumes:
  #mysql-data: