version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel_app_prod
    restart: unless-stopped
    volumes:
      - app-public:/var/www/public
    env_file:
      - .env
    networks:
      - laravel-prod

  web:
    image: nginx:alpine
    container_name: nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d/app.prod.conf:/etc/nginx/conf.d/default.conf  
      - app-public:/var/www/public
    depends_on:
      - app
    networks:
      - laravel-prod

networks:
  laravel-prod:
    driver: bridge
volumes:
  app-public:    